server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/auth/**

        - id: notification-server
          uri: lb://notification-server
          predicates:
            - Path=/notifications/**
          filters:
            - Authentication

        - id: recipient-server
          uri: lb://recipient-server
          predicates:
            - Path=/recipients/**
          filters:
            - Authentication

        - id: template-server
          uri: lb://template-server
          predicates:
            - Path=/templates/**
          filters:
            - Authentication


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

urls:
  validate: http://localhost:8080/auth/validate