server:
  port: 8094
  servlet:
    context-path: /templates

spring:
  application:
    name: template-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
    partitions: 3
    topics:
      recipient-update: recipient-updated
      template-update: template-updated
  datasource:
    url: jdbc:mysql://localhost:3306/templates_db
    username: mysql_user
    password: 12345Asd
  jpa:
    hibernate:
      ddl-auto: update

servers:
  recipient: recipient-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
