server:
  port: 8096

spring:
  application:
    name: sender-server
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      email: email-notification
      phone: phone-notification

servers:
  notification: notification-server

notification:
  max-retry-attempts: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true