server:
  port: 8090
  servlet:
    context-path: /auth

spring:
  application:
    name: authentication-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
