server:
  port: 8095
  servlet:
    context-path: /notifications

spring:
  application:
    name: notification-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      partitions: 10
      notifications:
        email: email-notification
        phone: phone-notification
      splitter: recipient-list-splitter
  datasource:
    url: jdbc:mysql://localhost:3306/notifications_db
    username: mysql_user
    password: 12345Asd
  jpa:
    hibernate:
      ddl-auto: update

servers:
  recipient: recipient-server
  template: template-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true